PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL
);
INSERT INTO "COMPANY" VALUES(1,'Paul',32,'California',20000.0);
INSERT INTO "COMPANY" VALUES(2,'Allen',25,'Texas',15000.0);
INSERT INTO "COMPANY" VALUES(3,'Teddy',23,'Norway',20000.0);
INSERT INTO "COMPANY" VALUES(4,'Mark',25,'Rich-Mond ',65000.0);
INSERT INTO "COMPANY" VALUES(5,'David',27,'Texas',85000.0);
INSERT INTO "COMPANY" VALUES(6,'Kim',22,'South-Hall',45000.0);
INSERT INTO "COMPANY" VALUES(7,'James',24,'Houston',10000.0);
COMMIT;
